# Generated by Django 5.0.1 on 2025-11-15 02:21

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "banner_title",
                    models.CharField(
                        default="발효홍삼 건강식품",
                        max_length=200,
                        verbose_name="배너 제목",
                    ),
                ),
                (
                    "banner_subtitle",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="배너 부제목"
                    ),
                ),
                (
                    "intro_title",
                    models.CharField(
                        default="프리미엄 6년근 발효홍삼",
                        max_length=200,
                        verbose_name="소개 제목",
                    ),
                ),
                (
                    "intro_text",
                    wagtail.fields.RichTextField(blank=True, verbose_name="소개 내용"),
                ),
            ],
            options={
                "verbose_name": "홈페이지",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NoticeDetailPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("date", models.DateField(verbose_name="공지 날짜")),
                (
                    "author",
                    models.CharField(
                        default="관리자", max_length=100, verbose_name="작성자"
                    ),
                ),
                ("body", wagtail.fields.RichTextField(verbose_name="내용")),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="중요 공지"),
                ),
            ],
            options={
                "verbose_name": "공지사항",
                "ordering": ["-date"],
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NoticePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "introduction",
                    wagtail.fields.RichTextField(blank=True, verbose_name="소개글"),
                ),
            ],
            options={
                "verbose_name": "공지사항 목록",
            },
            bases=("wagtailcore.page",),
        ),
    ]
