# Generated by Django 5.0.1 on 2025-11-15 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "장바구니",
                "verbose_name_plural": "장바구니 목록",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="주문번호"
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(max_length=100, verbose_name="수령인"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="전화번호")),
                ("address", models.TextField(verbose_name="주소")),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="우편번호"),
                ),
                (
                    "delivery_memo",
                    models.TextField(blank=True, verbose_name="배송 메모"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "결제 대기"),
                            ("paid", "결제 완료"),
                            ("processing", "상품 준비중"),
                            ("shipped", "배송중"),
                            ("delivered", "배송 완료"),
                            ("cancelled", "주문 취소"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="주문 상태",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="상품 금액"
                    ),
                ),
                (
                    "shipping_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="배송비",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="할인 금액",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="총 금액"
                    ),
                ),
                (
                    "points_used",
                    models.IntegerField(default=0, verbose_name="사용 포인트"),
                ),
                (
                    "points_earned",
                    models.IntegerField(default=0, verbose_name="적립 포인트"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="주문일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="주문자",
                    ),
                ),
            ],
            options={
                "verbose_name": "주문",
                "verbose_name_plural": "주문 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="제품명"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="가격"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="수량")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="주문",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="제품",
                    ),
                ),
            ],
            options={
                "verbose_name": "주문 아이템",
                "verbose_name_plural": "주문 아이템 목록",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("card", "신용/체크카드"),
                            ("bank", "무통장입금"),
                            ("vbank", "가상계좌"),
                            ("phone", "휴대폰"),
                            ("paypal", "PayPal"),
                        ],
                        max_length=20,
                        verbose_name="결제 방법",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                            ("cancelled", "취소"),
                            ("refunded", "환불"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="결제 상태",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="결제 금액"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="거래 ID"
                    ),
                ),
                (
                    "pg_provider",
                    models.CharField(blank=True, max_length=50, verbose_name="PG사"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="결제일시"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="orders.order",
                        verbose_name="주문",
                    ),
                ),
            ],
            options={
                "verbose_name": "결제",
                "verbose_name_plural": "결제 목록",
            },
        ),
        migrations.CreateModel(
            name="Shipping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carrier",
                    models.CharField(blank=True, max_length=50, verbose_name="택배사"),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="운송장 번호"
                    ),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="발송일시"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="배송완료일시"
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping",
                        to="orders.order",
                        verbose_name="주문",
                    ),
                ),
            ],
            options={
                "verbose_name": "배송",
                "verbose_name_plural": "배송 목록",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="수량"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="추가일"),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.cart",
                        verbose_name="장바구니",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="제품",
                    ),
                ),
            ],
            options={
                "verbose_name": "장바구니 아이템",
                "verbose_name_plural": "장바구니 아이템 목록",
                "unique_together": {("cart", "product")},
            },
        ),
    ]
