# Generated by Django 5.0.1 on 2025-11-15 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="전화번호"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="주소")),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="우편번호"
                    ),
                ),
                ("points", models.IntegerField(default=0, verbose_name="포인트")),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("bronze", "브론즈"),
                            ("silver", "실버"),
                            ("gold", "골드"),
                            ("platinum", "플래티넘"),
                        ],
                        default="bronze",
                        max_length=20,
                        verbose_name="등급",
                    ),
                ),
                (
                    "marketing_agreed",
                    models.BooleanField(default=False, verbose_name="마케팅 수신 동의"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="가입일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 프로필",
                "verbose_name_plural": "사용자 프로필 목록",
            },
        ),
    ]
